artifacts_root: artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_url : https://github.com/ishu-cs/Datasets/raw/main/Samsum_Data.zip
  local_data_file : artifacts/data_ingestion/samsum_Data.zip
  unzip_dir : artifacts/data_ingestion/